site_name: src
site_description: Its about a website to upload ads
repo_url: https://github.com/cafadev/src-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/cafadev">cafadev</a>.
dev_addr: 0.0.0.0:9000

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
